schema_version = "1.0.0"
id = "treegen"
version = "2.7.4"
name = "Tree Gen LLM"
tagline = "A Blender addon for generating Tree"
maintainer = "yuuto"
type = "add-on"
blender_version_min = "4.3.0"
license = [
    "MIT"
]
tags = [
    "Mesh",
    "Modeling",
    "Node",
    "Object",
    "Add Mesh",
    "System",
    "Pipeline",
    "User Interface",
]
wheels = [
    "wheels/certifi-2025.1.31-py3-none-any.whl",
    "wheels/charset_normalizer-3.4.1-cp311-cp311-win_amd64.whl",
    "wheels/colorama-0.4.6-py2.py3-none-any.whl",
    "wheels/diskcache-5.6.3-py3-none-any.whl",
    "wheels/filelock-3.17.0-py3-none-any.whl",
    "wheels/fsspec-2025.3.0-py3-none-any.whl",
    "wheels/huggingface_hub-0.29.2-py3-none-any.whl",
    "wheels/idna-3.10-py3-none-any.whl",
    "wheels/jinja2-3.1.6-py3-none-any.whl",
    "wheels/llama_cpp_python-0.2.90-cp311-cp311-win_amd64.whl",
    "wheels/MarkupSafe-3.0.2-cp311-cp311-win_amd64.whl",
    "wheels/numpy-2.2.3-cp311-cp311-win_amd64.whl",
    "wheels/packaging-24.2-py3-none-any.whl",
    "wheels/PyYAML-6.0.2-cp311-cp311-win_amd64.whl",
    "wheels/requests-2.32.3-py3-none-any.whl",
    "wheels/tqdm-4.67.1-py3-none-any.whl",
    "wheels/typing_extensions-4.12.2-py3-none-any.whl",
    "wheels/urllib3-2.3.0-py3-none-any.whl",
]

[permissions]
network = "Download required models"
files = "Install required models"
